# Generated by Django 5.2.5 on 2025-10-01 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('cover_image', models.URLField(max_length=400)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('point_potential', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_status', models.CharField(choices=[('reading', 'Reading'), ('to-read', 'To-Read'), ('read', 'Read')], default='to-read', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_complete', models.PositiveIntegerField(default=0)),
                ('points_earned', models.PositiveIntegerField()),
                ('entry', models.TextField()),
                ('date_of_entry', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('user_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='books.userbook')),
            ],
        ),
    ]
