# Generated by Django 5.2.5 on 2025-09-11 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='')),
                ('page_count', models.PositiveIntegerField()),
                ('point_potential', models.PositiveIntegerField()),
                ('reading_status', models.CharField(choices=[('to-read', 'To Read'), ('reading', 'Currently Reading'), ('read', 'Read')], default='to-read', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_complete', models.PositiveIntegerField()),
                ('points_earned', models.PositiveIntegerField()),
                ('entry', models.TextField()),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='books.book')),
            ],
        ),
    ]
