# Generated by Django 5.2.5 on 2025-10-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='current_progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
