# Generated by Django 5.2.5 on 2025-09-23 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover_image_alter_book_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readinglog',
            name='date_of_entry',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='readinglog',
            name='percentage_complete',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
