# Generated by Django 5.2.5 on 2025-09-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='books_read_count',
            new_name='books_read',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='words_written_count',
            new_name='words_written',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='entries_made_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='entries_made',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='pages_read',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='global_rank',
            field=models.PositiveBigIntegerField(default=None),
        ),
    ]
