# Generated by Django 5.2.5 on 2025-09-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_books_read_count_profile_books_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='global_rank',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
