# Generated by Django 5.2.5 on 2025-09-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_global_rank_profile_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
